/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package gui.internal;

import gui.main.iWindow;
import iRecord.Controller.ArtistManager;
import java.awt.Color;
import java.util.Date;
import java.util.Random;
/**
 *
 * @author nisan
 */
public class frmAddArtist extends javax.swing.JInternalFrame {
    private String artistID;
    private String stageName;
    private String Email;
    private String password;
    private Date Exipred;
    
    /**
     * Creates new form frmCreateSession
     */
    public frmAddArtist() {
        setTitle("Add Artist Page");
        initComponents();
        
        init();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblArtistID = new javax.swing.JLabel();
        lblStageName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPass2 = new javax.swing.JLabel();
        lblPass1 = new javax.swing.JLabel();
        lblMailError = new javax.swing.JLabel();
        tfStageName = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        lblPass4 = new javax.swing.JLabel();
        lbNameError = new javax.swing.JLabel();
        Pass1 = new javax.swing.JPasswordField();
        Pass2 = new javax.swing.JPasswordField();

        setBackground(new Color(0,0,0,0));
        getContentPane().setLayout(null);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Add Artist");
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 230, 110, 23);

        jLabel16.setBackground(new Color(0,0,0,0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Add new artist window");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 0, 360, 30);

        lblID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("Artist id");
        getContentPane().add(lblID);
        lblID.setBounds(150, 50, 110, 15);

        lblArtistID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblArtistID.setForeground(new java.awt.Color(255, 255, 255));
        lblArtistID.setText("Artist ID");
        getContentPane().add(lblArtistID);
        lblArtistID.setBounds(10, 50, 110, 15);

        lblStageName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStageName.setForeground(new java.awt.Color(255, 255, 255));
        lblStageName.setText("Stage Name");
        getContentPane().add(lblStageName);
        lblStageName.setBounds(10, 80, 110, 15);

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(10, 105, 110, 20);

        lblPass2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPass2.setForeground(new java.awt.Color(255, 255, 255));
        lblPass2.setText("Retype Password");
        getContentPane().add(lblPass2);
        lblPass2.setBounds(10, 170, 110, 15);

        lblPass1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPass1.setForeground(new java.awt.Color(255, 255, 255));
        lblPass1.setText("Password");
        getContentPane().add(lblPass1);
        lblPass1.setBounds(10, 140, 110, 15);

        lblMailError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMailError.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblMailError);
        lblMailError.setBounds(330, 110, 280, 20);

        tfStageName.setText("Enter stage name");
        tfStageName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfStageNameFocusGained(evt);
            }
        });
        tfStageName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStageNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfStageName);
        tfStageName.setBounds(150, 80, 170, 20);

        tfEmail.setText("Enter Email");
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
        });
        getContentPane().add(tfEmail);
        tfEmail.setBounds(150, 110, 170, 20);

        lblPass4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPass4.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblPass4);
        lblPass4.setBounds(330, 170, 280, 20);

        lbNameError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNameError.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lbNameError);
        lbNameError.setBounds(330, 80, 280, 20);

        Pass1.setText("jPasswordField1");
        Pass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Pass1FocusGained(evt);
            }
        });
        getContentPane().add(Pass1);
        Pass1.setBounds(150, 140, 170, 20);

        Pass2.setText("jPasswordField2");
        Pass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Pass2FocusGained(evt);
            }
        });
        getContentPane().add(Pass2);
        Pass2.setBounds(150, 170, 170, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tfStageNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfStageNameFocusGained
        if (tfStageName.getText().equals("Enter stage name"))
            tfStageName.setText("");
    }//GEN-LAST:event_tfStageNameFocusGained
    
    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
        if (tfEmail.getText().equals("Enter Email"))
            tfEmail.setText("");
    }//GEN-LAST:event_tfEmailFocusGained
    
    private void Pass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Pass1FocusGained
        Pass1.setText("");
    }//GEN-LAST:event_Pass1FocusGained
    
    private void Pass2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Pass2FocusGained
        Pass2.setText("");
    }//GEN-LAST:event_Pass2FocusGained
    
    private void tfStageNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStageNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStageNameActionPerformed
    
    
    
    
    
    private void init(){
        createArtistID();
        
        
        
    }
    
    private void createArtistID(){
        Random rand = new Random();
        int num = 0;
        String tempID = null;
        while (ArtistManager.checkExistence(tempID) && num < 1000){
            num = rand.nextInt(9999);
            tempID = "AR"+num;
            
            if (ArtistManager.checkExistence(tempID))
                artistID = tempID;
        }
        
        iWindow.log("Found empty ID for artist " + artistID);
                
    }
    
    public void updateDate(){
        
        iWindow.update();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pass1;
    private javax.swing.JPasswordField Pass2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel lbNameError;
    private javax.swing.JLabel lblArtistID;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMailError;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblPass4;
    private javax.swing.JLabel lblStageName;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfStageName;
    // End of variables declaration//GEN-END:variables
}
