/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package gui.internal;

import Validators.EmailValidator;
import gui.main.iWindow;
import iRecord.Controller.RecordingManager;
import iRecord.Controller.StudioAndRoomManager;
import java.awt.Color;
import java.io.File;
import java.util.Random;

/**
 *
 * @author nisan
 */
public class frmAddRecording extends javax.swing.JInternalFrame {
    private int studioID, length, min, sec;
    private String lyrics, name, url, status, recID, prevRec;
    private File file;

    
    /**
     * Creates new form frmCreateSession
     */
    public frmAddRecording(int studioID) {
        this.studioID = studioID;
        
        setTitle("Add Artist Page");
        initComponents();
        
        init();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        pnlAdd = new javax.swing.JPanel();
        lblStudio = new javax.swing.JLabel();
        lblRate = new javax.swing.JLabel();
        lblmaxMus = new javax.swing.JLabel();
        lblisloation = new javax.swing.JLabel();
        lblLyricsError = new javax.swing.JLabel();
        tfURL = new javax.swing.JTextField();
        lblTitleError = new javax.swing.JLabel();
        lblStudioID = new javax.swing.JLabel();
        cbState = new javax.swing.JComboBox<>();
        lblPhone1 = new javax.swing.JLabel();
        lblRecording = new javax.swing.JLabel();
        Min = new javax.swing.JComboBox<>();
        Sec = new javax.swing.JComboBox<>();
        tfTitle = new javax.swing.JTextField();
        lblRate1 = new javax.swing.JLabel();
        lblRate2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblURLError = new javax.swing.JLabel();
        lblisloation1 = new javax.swing.JLabel();
        tfTitle1 = new javax.swing.JTextField();
        lblprvERR = new javax.swing.JLabel();
        lblGen = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setBackground(new Color(0,0,0,0));
        getContentPane().setLayout(null);

        jLabel16.setBackground(new Color(0,0,0,0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Add new roon window");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 0, 360, 30);

        pnlAdd.setBackground(new Color(255,255,255,60));
        pnlAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStudio.setForeground(new java.awt.Color(255, 255, 255));
        lblStudio.setText("Studio ID");
        pnlAdd.add(lblStudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        lblRate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRate.setForeground(new java.awt.Color(255, 255, 255));
        lblRate.setText("URL");
        pnlAdd.add(lblRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, -1));

        lblmaxMus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblmaxMus.setForeground(new java.awt.Color(255, 255, 255));
        lblmaxMus.setText("Song Length");
        pnlAdd.add(lblmaxMus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, -1));

        lblisloation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblisloation.setForeground(new java.awt.Color(255, 255, 255));
        lblisloation.setText("Pervious Recording");
        pnlAdd.add(lblisloation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 130, -1));

        lblLyricsError.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblLyricsError.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblLyricsError, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 390, 20));

        tfURL.setText("Enter URL");
        tfURL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfURLFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfURLFocusLost(evt);
            }
        });
        pnlAdd.add(tfURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 190, -1));

        lblTitleError.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblTitleError.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblTitleError, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 390, 20));

        lblStudioID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStudioID.setForeground(new java.awt.Color(255, 255, 255));
        lblStudioID.setText("ID");
        pnlAdd.add(lblStudioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, -1));

        cbState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option", "Skeleton", "Demo", "Mastered" }));
        cbState.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbStateFocusLost(evt);
            }
        });
        pnlAdd.add(cbState, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 190, -1));

        lblPhone1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhone1.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone1.setText("Recording ID");
        pnlAdd.add(lblPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lblRecording.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRecording.setForeground(new java.awt.Color(255, 255, 255));
        lblRecording.setText("NUM");
        pnlAdd.add(lblRecording, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 190, -1));

        Min.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minutes", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        Min.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                MinFocusLost(evt);
            }
        });
        pnlAdd.add(Min, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 80, -1));

        Sec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minutes", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        Sec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SecFocusLost(evt);
            }
        });
        pnlAdd.add(Sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 80, -1));

        tfTitle.setText("Enter title");
        tfTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTitleFocusLost(evt);
            }
        });
        pnlAdd.add(tfTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, -1));

        lblRate1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRate1.setForeground(new java.awt.Color(255, 255, 255));
        lblRate1.setText("Song Title");
        pnlAdd.add(lblRate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));

        lblRate2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRate2.setForeground(new java.awt.Color(255, 255, 255));
        lblRate2.setText("Lyrics");
        pnlAdd.add(lblRate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, -1));

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lyrics");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        pnlAdd.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 190, 100));

        lblURLError.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblURLError.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblURLError, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 390, 20));

        lblisloation1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblisloation1.setForeground(new java.awt.Color(255, 255, 255));
        lblisloation1.setText("Recording Status");
        pnlAdd.add(lblisloation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, -1));

        tfTitle1.setText("Enter privious recording id");
        tfTitle1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTitle1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTitle1FocusLost(evt);
            }
        });
        pnlAdd.add(tfTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 190, -1));

        lblprvERR.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblprvERR.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblprvERR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 390, 20));

        getContentPane().add(pnlAdd);
        pnlAdd.setBounds(0, 40, 780, 350);

        lblGen.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblGen.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblGen);
        lblGen.setBounds(10, 460, 380, 20);

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Recording");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(10, 430, 160, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tfURLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfURLFocusGained
        if (tfURL.getText().equals("Enter url"))
            tfURL.setText("");
    }//GEN-LAST:event_tfURLFocusGained
                    
    private void tfURLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfURLFocusLost
        String temp = tfURL.getText();
        if (!EmailValidator.validateURL(temp)){
            lblTitleError.setText("Invalid URL");
            url = null;
            updateWin();
            return;
        }

        
        lblTitleError.setText("");
        url = temp;
        updateWin();
    }//GEN-LAST:event_tfURLFocusLost
                
    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        if (studioID < 1 || recID == null || min < 0 || sec < 0 || name == null || lyrics == null || url == null || file == null || status == null){
            lblGen.setText("One or more fields ane missing");
            updateWin();
            return;
        }
        else{
            
            
        }
         
    }//GEN-LAST:event_btnAddMouseClicked

    private void tfTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTitleFocusGained
        if (tfTitle.getText().equals("Enter title"))
            tfTitle.setText("");
        updateWin();
    }//GEN-LAST:event_tfTitleFocusGained

    private void tfTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTitleFocusLost
        if (tfTitle.getText().length() < 3){
        lblTitleError.setText("Must enter song name");
        name = null;
        updateWin();
        return;
        }
        
        name = tfTitle.getText();
        lblTitleError.setText("");
        updateWin();
        
    }//GEN-LAST:event_tfTitleFocusLost

    private void jTextArea1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea1FocusGained
        if (jTextArea1.getText().equals("Lyrics"))
            jTextArea1.setText("");
        updateWin();
    }//GEN-LAST:event_jTextArea1FocusGained

    private void jTextArea1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea1FocusLost

        if (jTextArea1.getText().length() < 20) {
            lblLyricsError.setText("You must add lyrics");
            
        }
        
        lblLyricsError.setText("");
        iWindow.update();

    }//GEN-LAST:event_jTextArea1FocusLost

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void MinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MinFocusLost
        if (Min.getSelectedIndex() == 0){
            min = -1;
            return;
        }
        
        min = Min.getSelectedIndex()-1;
        return;
    }//GEN-LAST:event_MinFocusLost

    private void SecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SecFocusLost
        if (Sec.getSelectedIndex() == 0){
            sec = -1;
            return;
        }
        
        sec = Min.getSelectedIndex()-1;
        return;
    }//GEN-LAST:event_SecFocusLost

    private void cbStateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbStateFocusLost
        if (cbState.getSelectedIndex() == 0) {
            status = null;
            return;
        }
        status = (String)cbState.getSelectedItem();
    }//GEN-LAST:event_cbStateFocusLost

    private void tfTitle1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTitle1FocusGained
        if (tfTitle1.getText().equals("Enter privious recording id"))
            tfTitle1.setText("");
    }//GEN-LAST:event_tfTitle1FocusGained

    private void tfTitle1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTitle1FocusLost
        String temp = tfTitle1.getText();
        
        //check if the recording belongs to the artist
        if (!RecordingManager.isArtistsRec(temp)){
            lblprvERR.setText("Recording doesn't belong to artist");
            updateWin();
            return;
        }
        
        String prevStatus = RecordingManager.getRecordingStatus(temp);
        if (prevStatus.equals("Sketlon") || prevStatus.equals("Demo") && status.equals("Mastered")){
            setRecordingStatus();
        }

        else if (prevStatus.equals("Sketlon") || status.equals("Demo")){
            setRecordingStatus();
        }

        else if (prevStatus.equals(status)){
            setRecordingStatus();
        }
        
        else{
            lblprvERR.setText("Privious status doesn't match current recrding status");
            updateWin();
            return;
        }
        
        
    }//GEN-LAST:event_tfTitle1FocusLost

        
    private void init(){
        lblStudioID.setText("" + studioID);
        
        initRecID(); 
    }
    
    /**
     * this method generates random id for artist
     * the generated id is checked by the controller before it's set
     */
    private void initRecID(){
        Random rand = new Random();
        int num = 0;
        String tempID = null;
        while (true){
            num = rand.nextInt(99999);
            if (num > 10000){
                tempID = "RE"+num;
                
                if (!RecordingManager.isExists(tempID)){
                    recID = tempID;
                    lblRecording.setText(tempID);
                    updateWin();
                    return;
                }
            }
        }

    }
    
    /**
     * Helper method for code reuse
     */
    private void setRecordingStatus(){
        
    }
    
    public void updateWin(){
        
        iWindow.update();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Min;
    private javax.swing.JComboBox<String> Sec;
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cbState;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblGen;
    private javax.swing.JLabel lblLyricsError;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblRate1;
    private javax.swing.JLabel lblRate2;
    private javax.swing.JLabel lblRecording;
    private javax.swing.JLabel lblStudio;
    private javax.swing.JLabel lblStudioID;
    private javax.swing.JLabel lblTitleError;
    private javax.swing.JLabel lblURLError;
    private javax.swing.JLabel lblisloation;
    private javax.swing.JLabel lblisloation1;
    private javax.swing.JLabel lblmaxMus;
    private javax.swing.JLabel lblprvERR;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTextField tfTitle1;
    private javax.swing.JTextField tfURL;
    // End of variables declaration//GEN-END:variables
}
