/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package gui.internal;

import Validators.EmailValidator;
import entities.*;
import gui.main.iWindow;
import iRecord.Controller.ArtistManager;
import iRecord.Controller.FreelancerManager;
import iRecord.Controller.StudioAndRoomManager;
import iRecord.Validators.CharValidator;
import iRecord.utilities.EAuth;
import java.awt.Color;
import java.util.Date;
import java.util.Map;
import java.util.Random;

/**
 *
 * @author nisan
 */
public class frmFreelancerToStudio extends javax.swing.JInternalFrame {
    private Freelancer f = null;
    private Studio s = null;
    private int rating = 0;
    
    /**
     * Creates new form frmCreateSession
     */
    public frmFreelancerToStudio() {
        setTitle("Add Artist Page");
        initComponents();
        
        init();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        pnlAdd = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblArtistID = new javax.swing.JLabel();
        lblStageName = new javax.swing.JLabel();
        tfArtistId = new javax.swing.JTextField();
        lblNameError = new javax.swing.JLabel();
        btnDisconnect = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        lblStudio = new javax.swing.JLabel();
        slctStudio = new javax.swing.JComboBox<>();
        cbRate = new javax.swing.JComboBox<>();
        lblStageName1 = new javax.swing.JLabel();
        lblGen = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,0));
        getContentPane().setLayout(null);

        jLabel16.setBackground(new Color(0,0,0,0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Connect and remove freelancer to studio");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 0, 360, 30);

        pnlAdd.setBackground(new Color(255,255,255,40));
        pnlAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Stage Name");
        pnlAdd.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 230, -1));

        lblArtistID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblArtistID.setForeground(new java.awt.Color(255, 255, 255));
        lblArtistID.setText("Freelancer ID");
        pnlAdd.add(lblArtistID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));

        lblStageName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStageName.setForeground(new java.awt.Color(255, 255, 255));
        lblStageName.setText("Stage Name");
        pnlAdd.add(lblStageName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        tfArtistId.setText("Enter freelancer id");
        tfArtistId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfArtistIdFocusGained(evt);
            }
        });
        pnlAdd.add(tfArtistId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 230, -1));

        lblNameError.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblNameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 290, 20));

        btnDisconnect.setText("Disconnect");
        btnDisconnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisconnectMouseClicked(evt);
            }
        });
        pnlAdd.add(btnDisconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, -1));

        btnConnect.setText("Connect");
        btnConnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConnectMouseClicked(evt);
            }
        });
        pnlAdd.add(btnConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 110, -1));

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });
        pnlAdd.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        lblStudio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStudio.setForeground(new java.awt.Color(255, 255, 255));
        lblStudio.setText("Select Studio");
        pnlAdd.add(lblStudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        slctStudio.setModel(new javax.swing.DefaultComboBoxModel<>(new Studio[] { new Studio("Select Studio") }));
        slctStudio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                slctStudioItemStateChanged(evt);
            }
        });
        pnlAdd.add(slctStudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 230, -1));

        cbRate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cbRate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRateItemStateChanged(evt);
            }
        });
        pnlAdd.add(cbRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 230, -1));

        lblStageName1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStageName1.setForeground(new java.awt.Color(255, 255, 255));
        lblStageName1.setText("Rating");
        pnlAdd.add(lblStageName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 20));

        getContentPane().add(pnlAdd);
        pnlAdd.setBounds(0, 40, 780, 200);

        lblGen.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblGen.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblGen);
        lblGen.setBounds(10, 260, 380, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tfArtistIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfArtistIdFocusGained
        if (tfArtistId.getText().equals("Enter freelancer id"))
            tfArtistId.setText("");
    }//GEN-LAST:event_tfArtistIdFocusGained

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        //import artist data
        
        f = FreelancerManager.getFreelancer(tfArtistId.getText());
                
        if (f == null){
            lblNameError.setText("Freelancer was not found");
            updateWin();
            return;
        }
        
        lblName.setText(f.getStageName());
        
        lblGen.setForeground(Color.GREEN);
        lblGen.setText("");
        lblNameError.setText("");
        updateWin();
        return;
        
    }//GEN-LAST:event_btnOKMouseClicked

    private void btnDisconnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisconnectMouseClicked
        if (f == null || s == null){
            
            lblGen.setForeground(Color.red);
            lblGen.setText("One or more fields are missing");
            updateWin();
            return;
        }
        
        if (!FreelancerManager.isWorkingWithStudio(f, s)){
            lblNameError.setText("Freelancer is not in studio");
            updateWin();
            return;
            
        }
        
        FreelancerManager.disconnectFreelancer(f, s);
        
        lblName.setText(f.getStageName());
        
        lblGen.setForeground(Color.GREEN);
        lblGen.setText("Done");
        updateWin();
        return;
        
        
    }//GEN-LAST:event_btnDisconnectMouseClicked

    private void btnConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseClicked
        if (f == null || s == null){
            
            lblGen.setForeground(Color.red);
            lblGen.setText("One or more fields are missing");
            updateWin();
            return;
        }
        
        if (FreelancerManager.isWorkingWithStudio(f, s)){
            FreelancerManager.disconnectFreelancer(f, s);
            updateWin();          
        }
        
        FreelancerManager.connectFreelancer(f, s, rating);
        
        //update artist data
        lblName.setText(f.getStageName());

        lblGen.setForeground(Color.GREEN);
        lblGen.setText("Done");
        updateWin();
        return;
        
    }//GEN-LAST:event_btnConnectMouseClicked

    private void slctStudioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_slctStudioItemStateChanged
        if (slctStudio.getSelectedIndex() == 0) return;
        s = (Studio) slctStudio.getSelectedItem();

        updateWin();
    }//GEN-LAST:event_slctStudioItemStateChanged

    
    private void cbRateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRateItemStateChanged
        rating = cbRate.getSelectedIndex();
    }//GEN-LAST:event_cbRateItemStateChanged
                                        
    private void init(){
        initStudios();
    }
    
    
    /**
     * this method generates random id for artist
     * the generated id is checked by the controller before it's set
     */
    private void initStudios(){
       Map<Integer,Studio> studios = StudioAndRoomManager.getStudios();
       for (Studio s:studios.values()){
           slctStudio.addItem(s);
       }
       
    }
   
    
    public void updateWin(){
        
        iWindow.update();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbRate;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel lblArtistID;
    private javax.swing.JLabel lblGen;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblStageName;
    private javax.swing.JLabel lblStageName1;
    private javax.swing.JLabel lblStudio;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JComboBox<Studio> slctStudio;
    private javax.swing.JTextField tfArtistId;
    // End of variables declaration//GEN-END:variables
}
