/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package gui.internal;

import gui.main.iWindow;
import iRecord.Controller.ArtistManager;
import iRecord.Controller.FreelancerManager;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nisan
 */
public class frmRegReport extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form frmCreateSession
     */
    public frmRegReport() {
        setTitle("Add Artist Page");
        initComponents();
        
        init();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        pnlAdd = new javax.swing.JPanel();
        lblStageName = new javax.swing.JLabel();
        lblSelectTable = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGen = new javax.swing.JTable();
        slcData = new javax.swing.JComboBox<>();
        cbSort = new javax.swing.JComboBox<>();
        getData = new javax.swing.JButton();

        setBackground(new Color(0,0,0,0));
        getContentPane().setLayout(null);

        jLabel16.setBackground(new Color(0,0,0,0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Artist suspeinsion window");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 0, 360, 30);

        pnlAdd.setBackground(new Color(255,255,255,40));
        pnlAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStageName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStageName.setForeground(new java.awt.Color(255, 255, 255));
        lblStageName.setText("Sort by");
        pnlAdd.add(lblStageName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));

        lblSelectTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectTable.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectTable.setText("Select Data");
        pnlAdd.add(lblSelectTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        tblGen = new javax.swing.JTable(){
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    case 2:
                    return String.class;

                    default:
                    return Object.class;
                }
            }
        };
        tblGen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Stage Name", "Email", "Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblGen);

        pnlAdd.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 680, 390));

        slcData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Data", "Artists", "Freelancers" }));
        slcData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                slcDataItemStateChanged(evt);
            }
        });
        pnlAdd.add(slcData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 230, -1));

        cbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort By", "ID", "Stage Name" }));
        pnlAdd.add(cbSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 230, -1));

        getData.setText("Get Data");
        getData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                getDataItemStateChanged(evt);
            }
        });
        getData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getDataMouseClicked(evt);
            }
        });
        pnlAdd.add(getData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 230, -1));

        getContentPane().add(pnlAdd);
        pnlAdd.setBounds(0, 40, 780, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void slcDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_slcDataItemStateChanged
        
    }//GEN-LAST:event_slcDataItemStateChanged

    private void getDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_getDataItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_getDataItemStateChanged

    private void getDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getDataMouseClicked
        if (slcData.getSelectedIndex() == 0 || cbSort.getSelectedIndex() == 0) return;

        //Artist is selected
        if (slcData.getSelectedIndex() == 1){

            //get all artists
            ArrayList <String[]> artists  = null;
            if(cbSort.getSelectedIndex() == 1) artists = ArtistManager.getArtistList("id");
            else if (cbSort.getSelectedIndex() == 2) artists = ArtistManager.getArtistList("stageName");
            
            DefaultTableModel model = (DefaultTableModel) tblGen.getModel();
            model.setRowCount(0);
            
            //while has next
            for (String[] s:artists){
                if (s == null) break;
                String[] row = {s[0], s[1], s[2], s[3]};
                model.addRow(row);
            }

        }

        //Freelancer is selected
        if (slcData.getSelectedIndex() == 2){
            
            //get all artists
            ArrayList <String[]> freelancers  = null;
            if(cbSort.getSelectedIndex() == 1) freelancers = FreelancerManager.getArtistList("id");
            else if (cbSort.getSelectedIndex() == 2) freelancers = FreelancerManager.getArtistList("stageName");
            
            DefaultTableModel model = (DefaultTableModel) tblGen.getModel();
            model.setRowCount(0);
            
            //while has next
            for (String[] s:freelancers){
                if (s == null) break;
                String[] row = {s[0], s[1], s[2], s[3]};
                model.addRow(row);
            }

            
            
        }
    }//GEN-LAST:event_getDataMouseClicked

                                            
    private void init(){
        
    }

   
    
    public void updateWin(){
        
        iWindow.update();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSort;
    private javax.swing.JButton getData;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblSelectTable;
    private javax.swing.JLabel lblStageName;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JComboBox<String> slcData;
    private javax.swing.JTable tblGen;
    // End of variables declaration//GEN-END:variables
}
