/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package gui.internal;

import Validators.PositiveValidator;
import entities.Artist;
import gui.main.iWindow;
import iRecord.Controller.RecordingManager;
import iRecord.iRecord;
import java.awt.Color;
import java.io.File;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nisan
 */
public class frmSessions extends javax.swing.JInternalFrame {
    private Artist a = null;
    private Date picked = null;
    private int studioID;
    private File file;
    
    
    /**
     * Creates new form frmCreateSession
     */
    public frmSessions() {
        
        initComponents();
        
        init();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        pnlAdd = new javax.swing.JPanel();
        lbldate = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGen = new javax.swing.JTable();
        getData = new javax.swing.JButton();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        lblAddr = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblstageName = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        btnAddFile = new javax.swing.JButton();

        setBackground(new Color(0,0,0,0));
        getContentPane().setLayout(null);

        jLabel16.setBackground(new Color(0,0,0,0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Artist's Sessions");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 0, 360, 30);

        pnlAdd.setBackground(new Color(255,255,255,40));
        pnlAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldate.setText("From Date");
        pnlAdd.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, -1));

        tblGen = new javax.swing.JTable(){
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    case 2:
                    return String.class;

                    default:
                    return Object.class;
                }
            }
        };
        tblGen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Studio ID", "Studio Name", "Session ID", "Date", "Total Cost", "Status", "Record ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblGen);

        pnlAdd.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 760, 140));

        getData.setText("Get Data");
        getData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getDataMouseClicked(evt);
            }
        });
        pnlAdd.add(getData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 230, -1));

        jXDatePicker1.setBackground(new Color(0,0,0,0));
        jXDatePicker1.setForeground(new java.awt.Color(204, 0, 153));
        jXDatePicker1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jXDatePicker1FocusLost(evt);
            }
        });
        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });
        pnlAdd.add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, 20));

        lblAddr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddr.setForeground(new java.awt.Color(255, 255, 255));
        lblAddr.setText("Artist ID");
        pnlAdd.add(lblAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 20));

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("Stage Name");
        pnlAdd.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 20));

        lblMail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMail.setForeground(new java.awt.Color(255, 255, 255));
        lblMail.setText("Email");
        pnlAdd.add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 20));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        pnlAdd.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 230, 20));

        lblID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");
        pnlAdd.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 230, 20));

        lblstageName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstageName.setForeground(new java.awt.Color(255, 255, 255));
        lblstageName.setText("Stage Name");
        pnlAdd.add(lblstageName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, 20));

        lblError.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setText(" ");
        pnlAdd.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 370, -1));

        btnAddFile.setText("Add Recording");
        btnAddFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddFileMouseClicked(evt);
            }
        });
        pnlAdd.add(btnAddFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, -1));

        getContentPane().add(pnlAdd);
        pnlAdd.setBounds(0, 40, 780, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void getDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getDataMouseClicked
        if (a == null || picked == null){
            lblError.setText("One or more fields are missing");
            updateWin();
            return;
        }
        
        
        DefaultTableModel model = (DefaultTableModel) tblGen.getModel();
        model.setRowCount(0);
        //get the sessions of selected studio
        Timestamp t = new Timestamp(picked.getTime());
        ArrayList <String[]> ses = RecordingManager.getArtistSessions(a.getID(), t);
        
        
        //while has next
        for (String[] s:ses){
            if (s == null) break;
            String[] row = {s[0], s[1], s[2], s[3], s[4], s[5], s[6]};
            model.addRow(row);
        }
        
        
        lblError.setText("");
        updateWin();
        return;
        
    }//GEN-LAST:event_getDataMouseClicked
    
    private void jXDatePicker1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jXDatePicker1FocusLost
        
    }//GEN-LAST:event_jXDatePicker1FocusLost
    
    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        picked = jXDatePicker1.getDate();
        
        updateWin();
        return;
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void btnAddFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddFileMouseClicked

        if (tblGen.getSelectedRow() < 0) return;
        String id = (String)tblGen.getModel().getValueAt(tblGen.getSelectedRow(), 0);
        System.out.println(id);
        studioID = (int) PositiveValidator.stringToNum(id);
        if (studioID < 1){
            lblError.setText("Please select session to add recording");
            updateWin();
            return;
        }
        frmAddRecording add = new frmAddRecording(studioID);
        iWindow.openWin(add);
    }//GEN-LAST:event_btnAddFileMouseClicked
    
    
    private void init(){
        a = (Artist)iRecord.getLoggedUser();
        lblstageName.setText(a.getStageName());
        lblEmail.setText(a.getEmail());
        lblID.setText(a.getID());
    }
    
    
    
    public void updateWin(){
        
        iWindow.update();
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFile;
    private javax.swing.JButton getData;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lblAddr;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblstageName;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JTable tblGen;
    // End of variables declaration//GEN-END:variables
}