/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package gui.internal;

import Validators.PositiveValidator;
import entities.Studio;
import gui.main.iWindow;
import iRecord.Controller.ReportManager;
import iRecord.Controller.StudioAndRoomManager;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nisan
 */
public class frmStudiosFreelancers extends javax.swing.JInternalFrame {
    private Studio s = null;
    
    

        public frmStudiosFreelancers(int studioID) {
        setTitle("Studio's Sessions");
        initComponents();
        setStudio(studioID);
        lblstudioID.setText(s.getsID()+"");
        lblEmail.setText(s.getsEmail());
        lblAddress.setText(s.getsAddress());
        lblPhoneNumber.setText(s.getsPhoneNum());
        
        initTable();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        pnlAdd = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGen = new javax.swing.JTable();
        lblstudioID = new javax.swing.JLabel();
        lblAddr = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblSelectTable2 = new javax.swing.JLabel();
        btnRate = new javax.swing.JButton();

        setBackground(new Color(0,0,0,0));
        getContentPane().setLayout(null);

        jLabel16.setBackground(new Color(0,0,0,0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Studio's Freelancers");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 0, 360, 30);

        pnlAdd.setBackground(new Color(255,255,255,40));
        pnlAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblGen = new javax.swing.JTable(){
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    case 2:
                    return String.class;

                    default:
                    return Object.class;
                }
            }
        };
        tblGen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Freelancer ID", "Stage Name", "Profession", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGenMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblGen);

        pnlAdd.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 680, 240));

        lblstudioID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstudioID.setForeground(new java.awt.Color(255, 255, 255));
        lblstudioID.setText("ID");
        pnlAdd.add(lblstudioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 230, -1));

        lblAddr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddr.setForeground(new java.awt.Color(255, 255, 255));
        lblAddr.setText("Address");
        pnlAdd.add(lblAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 20));

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("Phone Number");
        pnlAdd.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 20));

        lblMail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMail.setForeground(new java.awt.Color(255, 255, 255));
        lblMail.setText("Email");
        pnlAdd.add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 20));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        pnlAdd.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 230, 20));

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Address");
        pnlAdd.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 230, 20));

        lblPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setText("Studio Name");
        pnlAdd.add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 230, 20));

        lblError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setText(" ");
        pnlAdd.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 370, -1));

        lblSelectTable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectTable2.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectTable2.setText("Select Studio");
        pnlAdd.add(lblSelectTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        btnRate.setText("Rate Freelancer");
        btnRate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRateMouseClicked(evt);
            }
        });
        pnlAdd.add(btnRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 160, -1));

        getContentPane().add(pnlAdd);
        pnlAdd.setBounds(0, 40, 780, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents
                
    private void tblGenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGenMouseClicked

        updateWin();
    }//GEN-LAST:event_tblGenMouseClicked

    private void btnRateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRateMouseClicked
        String flid = (String)tblGen.getModel().getValueAt(tblGen.getSelectedRow(), 0);
        frmFreelancerToStudio add = new  frmFreelancerToStudio(s, flid);
        iWindow.openWin(add);
        updateWin();
    }//GEN-LAST:event_btnRateMouseClicked
    
    
    private void init(){
        
    }

    
    //set studio
    private void setStudio(int StudioID){
        Map<Integer,Studio> studios = StudioAndRoomManager.getStudios();
        for (Studio s:studios.values()){
            if (s.getsID() == StudioID){
                this.s = s;
            }
        }
    }
    
    //set table values
    private void initTable(){
        ArrayList<String[]> temp = StudioAndRoomManager.getStudioFreelancers(s.getsID());
        if (temp == null) return;
        DefaultTableModel model = (DefaultTableModel) tblGen.getModel();
        model.setRowCount(0);
        for (String[]s : temp){
            if (s == null) break;
            model.addRow(s);
        }
    }
    
    
    
    public void updateWin(){
        
        iWindow.update();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRate;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddr;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSelectTable2;
    private javax.swing.JLabel lblstudioID;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JTable tblGen;
    // End of variables declaration//GEN-END:variables
}
