/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package gui.internal;

import ex2design.iMuzaMusic;
import entities.Artist;
import entities.Person;
import ex2design.utilities.EArtistStatus;
import ex2design.utilities.EAuth;
import gui.main.iWindow;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.SysexMessage;

/**
 *
 * @author nisan
 */
public class frmWatchArtists extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form frmTemplate
     */
    private static Artist art = null;
    private ResultSet r;
    public frmWatchArtists() {
        
        initComponents();
        setTitle("Watch Artists");
        pnlArtist.setVisible(false);
        slctArtist.setBackground(Color.black);
        slctArtist.setForeground(Color.white);
        slctArtist.removeAllItems();
        slctArtist.addItem("Select an artist");
        slctArtist.setSelectedIndex(0);
        r = iMuzaMusic.getDB().query("select * from Artists");
        try {
            while(r.next()){
                String ArtistID = r.getString("ArtistID");
                String strStageName = r.getString("strStageName");
                slctArtist.addItem(strStageName+" ("+ArtistID+")");
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmWatchArtists.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        slctArtist = new javax.swing.JComboBox<>();
        pnlArtist = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        lblArtistID = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtStageName = new javax.swing.JLabel();
        lblStageName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        lblFreeze = new javax.swing.JLabel();
        lblFacebook = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtBio = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();

        setIconifiable(true);
        getContentPane().setLayout(null);

        jLabel16.setBackground(new Color(0,0,0,0));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("You may choose an artist by using the selector.");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 30, 228, 14);

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/search.png"))); // NOI18N
        getContentPane().add(lblSearch);
        lblSearch.setBounds(20, 50, 30, 30);

        slctArtist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        slctArtist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                slctArtistItemStateChanged(evt);
            }
        });
        slctArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctArtistActionPerformed(evt);
            }
        });
        getContentPane().add(slctArtist);
        slctArtist.setBounds(60, 50, 240, 30);

        pnlArtist.setBackground(new Color(0,0,0,0));
        pnlArtist.setLayout(null);
        pnlArtist.add(jSeparator2);
        jSeparator2.setBounds(30, 50, 210, 0);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setEnabled(false);
        pnlArtist.add(jSeparator4);
        jSeparator4.setBounds(10, 40, 30, 10);

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlArtist.add(jSeparator5);
        jSeparator5.setBounds(10, 40, 10, 350);

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        pnlArtist.add(jSeparator6);
        jSeparator6.setBounds(10, 390, 570, 10);

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        pnlArtist.add(jSeparator7);
        jSeparator7.setBounds(130, 40, 450, 10);

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlArtist.add(jSeparator8);
        jSeparator8.setBounds(580, 40, 10, 350);

        lblArtistID.setForeground(new java.awt.Color(255, 255, 255));
        lblArtistID.setText("id");
        pnlArtist.add(lblArtistID);
        lblArtistID.setBounds(210, 60, 70, 14);

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("Artist ID");
        pnlArtist.add(txtID);
        txtID.setBounds(20, 60, 70, 16);

        lblEmailAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailAddress.setText("address");
        pnlArtist.add(lblEmailAddress);
        lblEmailAddress.setBounds(210, 120, 200, 14);

        txtStageName.setBackground(new java.awt.Color(255, 255, 255));
        txtStageName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtStageName.setForeground(new java.awt.Color(255, 255, 255));
        txtStageName.setText("Stage Name");
        pnlArtist.add(txtStageName);
        txtStageName.setBounds(20, 80, 90, 16);

        lblStageName.setForeground(new java.awt.Color(255, 255, 255));
        lblStageName.setText("name");
        pnlArtist.add(lblStageName);
        lblStageName.setBounds(210, 80, 210, 20);

        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Artist Details");
        pnlArtist.add(lblTitle);
        lblTitle.setBounds(50, 20, 100, 40);

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Email Address");
        pnlArtist.add(txtEmail);
        txtEmail.setBounds(20, 120, 110, 16);

        lblFreeze.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblFreeze.setForeground(new java.awt.Color(51, 102, 255));
        lblFreeze.setText("[Freeze Agent]");
        lblFreeze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFreezeMouseClicked(evt);
            }
        });
        pnlArtist.add(lblFreeze);
        lblFreeze.setBounds(490, 90, 80, 20);

        lblFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Facebook-Download-PNG.png"))); // NOI18N
        pnlArtist.add(lblFacebook);
        lblFacebook.setBounds(510, 50, 50, 40);

        txtStatus.setBackground(new java.awt.Color(255, 255, 255));
        txtStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 255, 255));
        txtStatus.setText("Status");
        pnlArtist.add(txtStatus);
        txtStatus.setBounds(20, 100, 110, 16);

        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("status");
        pnlArtist.add(lblStatus);
        lblStatus.setBounds(210, 100, 200, 14);

        txtBio.setBackground(new Color(0,0,0,0));
        txtBio.setForeground(new java.awt.Color(255, 255, 255));
        txtBio.setText("lblPhone");
        txtBio.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlArtist.add(txtBio);
        txtBio.setBounds(20, 150, 490, 200);

        getContentPane().add(pnlArtist);
        pnlArtist.setBounds(10, 100, 690, 420);

        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/back.png"))); // NOI18N
        lblBack.setLabelFor(lblBack);
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack);
        lblBack.setBounds(330, 50, 30, 30);

        lblNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/next.png"))); // NOI18N
        lblNext.setLabelFor(lblBack);
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        getContentPane().add(lblNext);
        lblNext.setBounds(380, 50, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void slctArtistItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_slctArtistItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Object item = evt.getItem();
            if (item.equals("Select an artist")) {
                pnlArtist.setVisible(false);
                return;
            }
            // do something with object
            String agID = iMuzaMusic.getID(slctArtist.getSelectedItem().toString());
            
            this.art = iMuzaMusic.getAgentEntity(agID);
            

            updateData();
        }
    }//GEN-LAST:event_slctArtistItemStateChanged
    
    private void slctArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctArtistActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_slctArtistActionPerformed
    
    private void lblFreezeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFreezeMouseClicked
        
        //Freeze Agent
    }//GEN-LAST:event_lblFreezeMouseClicked
    
    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        
        //can't be longer than max index
        if ((slctArtist.getSelectedIndex()+1) > slctArtist.getItemCount()){
            //pnlArtist.setVisible(false);
            return;
        }
        //get the correct object details
        else{
            slctArtist.setSelectedIndex(slctArtist.getSelectedIndex()+1);
            String agID = iMuzaMusic.getID(slctArtist.getSelectedItem().toString());
            this.art = iMuzaMusic.getAgentEntity(agID);
        }
        
        iMuzaMusic.getDB().query("select * from tbl");
        
        updateData();
        
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        
        //can't be less than 0
        if (slctArtist.getSelectedIndex()-1 < 1){            
            return;
        }
        //get the correct object details
        else{
            slctArtist.setSelectedIndex(slctArtist.getSelectedIndex()-1);
            String agID = iMuzaMusic.getID(slctArtist.getSelectedItem().toString());
            this.art = iMuzaMusic.getAgentEntity(agID);
            
        }
        
        
        updateData();
        
    }//GEN-LAST:event_lblBackMouseClicked
    
    public void updateData(){
        
        if(art!=null){
            //Artist chosen
            lblArtistID.setText(art.getID());
            txtBio.setText(art.getBiography());

            lblStageName.setText(art.getStageName());
            lblStatus.setText(art.getArStatus().toString());
            lblEmailAddress.setText(art.getEmailAddr());
                //treat fb
                //end fb
            pnlArtist.setVisible(false);
            pnlArtist.setVisible(true);

        }

        iWindow.update();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblArtistID;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblFacebook;
    private javax.swing.JLabel lblFreeze;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStageName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlArtist;
    private javax.swing.JComboBox<String> slctArtist;
    private javax.swing.JLabel txtBio;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtStageName;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
