/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package gui.main;

import entities.Artist;
import entities.Musician;
import entities.Soundman;
import gui.internal.*;
import iRecord.Controller.ArtistManager;
import iRecord.Controller.FreelancerManager;
import iRecord.Controller.XMLManager;
import iRecord.iRecord;
import iRecord.utilities.EAuth;
import java.sql.SQLException;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class MainGui extends javax.swing.JFrame {
    
    /**
     * Creates new form MainGui
     */
    public MainGui() throws SQLException {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        iWindow.setPanel(ContentFrame);
        iWindow.setLblTitle(lblTitle);
        refreshVars();
        
        
        
        iWindow.setPanel(ContentFrame);
        iWindow.setLblTitle(lblTitle);
        
        
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUsernames = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        AR = new javax.swing.JPanel();
        AddArtist = new javax.swing.JLabel();
        SuspendArtist = new javax.swing.JLabel();
        Sessions = new javax.swing.JLabel();
        STD = new javax.swing.JPanel();
        AddRoom = new javax.swing.JLabel();
        AddStudio = new javax.swing.JLabel();
        Artist = new javax.swing.JLabel();
        FL = new javax.swing.JPanel();
        AddSoundman = new javax.swing.JLabel();
        AddMusician = new javax.swing.JLabel();
        SuspendFreelancer = new javax.swing.JLabel();
        SuspendFreelancer1 = new javax.swing.JLabel();
        WatchRegistered = new javax.swing.JLabel();
        Freelancer = new javax.swing.JLabel();
        Expertise = new javax.swing.JLabel();
        Studio = new javax.swing.JLabel();
        pnlArtist = new javax.swing.JPanel();
        CreateSession1 = new javax.swing.JLabel();
        WatchRegistered1 = new javax.swing.JLabel();
        Sessions1 = new javax.swing.JLabel();
        ContentFrame = new javax.swing.JPanel();
        pnlFreelancer = new javax.swing.JPanel();
        joinStudio = new javax.swing.JLabel();
        WatchRegistered2 = new javax.swing.JLabel();
        Sessions2 = new javax.swing.JLabel();
        music = new javax.swing.JLabel();
        sound = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        HIA = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 766));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Page Title");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 240, 20));

        lblUsernames.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsernames.setForeground(new java.awt.Color(255, 255, 255));
        lblUsernames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsernames.setText("First Name");
        getContentPane().add(lblUsernames, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 200, 30));

        lblUserType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserType.setText("User Type");
        getContentPane().add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 30));

        pnlAdmin.setOpaque(false);

        AR.setBackground(new Color (0,0,0,120));
        AR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ARFocusLost(evt);
            }
        });

        AddArtist.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddArtist.setForeground(new java.awt.Color(255, 255, 255));
        AddArtist.setText("Add Artist");
        AddArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddArtistMouseClicked(evt);
            }
        });

        SuspendArtist.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SuspendArtist.setForeground(new java.awt.Color(255, 255, 255));
        SuspendArtist.setText("Suspend Artist");
        SuspendArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuspendArtistMouseClicked(evt);
            }
        });

        Sessions.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Sessions.setForeground(new java.awt.Color(255, 255, 255));
        Sessions.setText("Sessions");
        Sessions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SessionsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ARLayout = new javax.swing.GroupLayout(AR);
        AR.setLayout(ARLayout);
        ARLayout.setHorizontalGroup(
            ARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SuspendArtist, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(Sessions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ARLayout.setVerticalGroup(
            ARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ARLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(AddArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sessions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SuspendArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        STD.setBackground(new Color (0,0,0,120));
        STD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                STDFocusLost(evt);
            }
        });

        AddRoom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddRoom.setForeground(new java.awt.Color(255, 255, 255));
        AddRoom.setText("Add Room");
        AddRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddRoomMouseClicked(evt);
            }
        });

        AddStudio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddStudio.setForeground(new java.awt.Color(255, 255, 255));
        AddStudio.setText("Add Studio");
        AddStudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddStudioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout STDLayout = new javax.swing.GroupLayout(STD);
        STD.setLayout(STDLayout);
        STDLayout.setHorizontalGroup(
            STDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(STDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddStudio, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
        );
        STDLayout.setVerticalGroup(
            STDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddRoom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Artist.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Artist.setForeground(new java.awt.Color(255, 255, 255));
        Artist.setText("Artist");
        Artist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArtistMouseClicked(evt);
            }
        });

        FL.setBackground(new Color (0,0,0,120));
        FL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FLFocusLost(evt);
            }
        });

        AddSoundman.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddSoundman.setForeground(new java.awt.Color(255, 255, 255));
        AddSoundman.setText("Add Soundman");
        AddSoundman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddSoundmanMouseClicked(evt);
            }
        });

        AddMusician.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddMusician.setForeground(new java.awt.Color(255, 255, 255));
        AddMusician.setText("Add Musician");
        AddMusician.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMusicianMouseClicked(evt);
            }
        });

        SuspendFreelancer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SuspendFreelancer.setForeground(new java.awt.Color(255, 255, 255));
        SuspendFreelancer.setText("Suspend");
        SuspendFreelancer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuspendFreelancerMouseClicked(evt);
            }
        });

        SuspendFreelancer1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SuspendFreelancer1.setForeground(new java.awt.Color(255, 255, 255));
        SuspendFreelancer1.setText("Add to Studio");
        SuspendFreelancer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuspendFreelancer1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FLLayout = new javax.swing.GroupLayout(FL);
        FL.setLayout(FLLayout);
        FLLayout.setHorizontalGroup(
            FLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddMusician, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuspendFreelancer1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSoundman, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuspendFreelancer, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        FLLayout.setVerticalGroup(
            FLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FLLayout.createSequentialGroup()
                .addComponent(AddMusician, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(AddSoundman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SuspendFreelancer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SuspendFreelancer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        WatchRegistered.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        WatchRegistered.setForeground(new java.awt.Color(255, 255, 255));
        WatchRegistered.setText("Watch Registered");
        WatchRegistered.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WatchRegisteredMouseClicked(evt);
            }
        });

        Freelancer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Freelancer.setForeground(new java.awt.Color(255, 255, 255));
        Freelancer.setText("Freelancer");
        Freelancer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FreelancerMouseClicked(evt);
            }
        });

        Expertise.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Expertise.setForeground(new java.awt.Color(255, 255, 255));
        Expertise.setText("Expertise");
        Expertise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpertiseMouseClicked(evt);
            }
        });

        Studio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Studio.setForeground(new java.awt.Color(255, 255, 255));
        Studio.setText("Studio");
        Studio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addComponent(Artist, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addComponent(Studio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(STD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WatchRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Freelancer, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Expertise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(FL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addComponent(Artist, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(WatchRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addComponent(Freelancer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Expertise, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Studio, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(STD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 350, 350));

        pnlArtist.setOpaque(false);

        CreateSession1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CreateSession1.setForeground(new java.awt.Color(255, 255, 255));
        CreateSession1.setText("Create Session");
        CreateSession1.setToolTipText("");
        CreateSession1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateSession1MouseClicked(evt);
            }
        });

        WatchRegistered1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        WatchRegistered1.setForeground(new java.awt.Color(255, 255, 255));
        WatchRegistered1.setText("Watch Registered");
        WatchRegistered1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WatchRegistered1MouseClicked(evt);
            }
        });

        Sessions1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Sessions1.setForeground(new java.awt.Color(255, 255, 255));
        Sessions1.setText("Sessions");
        Sessions1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sessions1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlArtistLayout = new javax.swing.GroupLayout(pnlArtist);
        pnlArtist.setLayout(pnlArtistLayout);
        pnlArtistLayout.setHorizontalGroup(
            pnlArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArtistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArtistLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CreateSession1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlArtistLayout.createSequentialGroup()
                        .addGroup(pnlArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WatchRegistered1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sessions1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlArtistLayout.setVerticalGroup(
            pnlArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArtistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateSession1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WatchRegistered1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sessions1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        getContentPane().add(pnlArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 540));

        ContentFrame.setBackground(new Color(0,0,0,0));
        ContentFrame.setForeground(new java.awt.Color(255, 51, 102));
        ContentFrame.setAutoscrolls(true);
        ContentFrame.setOpaque(false);
        ContentFrame.setVisible(false);
        ContentFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContentFrameMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout ContentFrameLayout = new javax.swing.GroupLayout(ContentFrame);
        ContentFrame.setLayout(ContentFrameLayout);
        ContentFrameLayout.setHorizontalGroup(
            ContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        ContentFrameLayout.setVerticalGroup(
            ContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(ContentFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 830, 700));

        pnlFreelancer.setOpaque(false);

        joinStudio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        joinStudio.setForeground(new java.awt.Color(255, 255, 255));
        joinStudio.setText("Join Studio");
        joinStudio.setToolTipText("");
        joinStudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinStudioMouseClicked(evt);
            }
        });

        WatchRegistered2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        WatchRegistered2.setForeground(new java.awt.Color(255, 255, 255));
        WatchRegistered2.setText("Watch Registered");
        WatchRegistered2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WatchRegistered2MouseClicked(evt);
            }
        });

        Sessions2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Sessions2.setForeground(new java.awt.Color(255, 255, 255));
        Sessions2.setText("Sessions");
        Sessions2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sessions2MouseClicked(evt);
            }
        });

        music.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        music.setForeground(new java.awt.Color(255, 255, 255));
        music.setText("Edit Musician");
        music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicMouseClicked(evt);
            }
        });

        sound.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sound.setForeground(new java.awt.Color(255, 255, 255));
        sound.setText("Edit Soundman");
        sound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soundMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlFreelancerLayout = new javax.swing.GroupLayout(pnlFreelancer);
        pnlFreelancer.setLayout(pnlFreelancerLayout);
        pnlFreelancerLayout.setHorizontalGroup(
            pnlFreelancerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFreelancerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFreelancerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFreelancerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(joinStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFreelancerLayout.createSequentialGroup()
                        .addGroup(pnlFreelancerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WatchRegistered2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sessions2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sound, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(music, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlFreelancerLayout.setVerticalGroup(
            pnlFreelancerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFreelancerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(joinStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WatchRegistered2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sessions2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sound, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(music, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        getContentPane().add(pnlFreelancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 540));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/iStudioGui.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1020, 770));

        btnExit.setText("jButton1");
        btnExit.setEnabled(false);
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        btnExit.setRequestFocusEnabled(false);
        btnExit.setRolloverEnabled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 160, 40));

        btnLogout.setText("jButton1");
        btnLogout.setEnabled(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setFocusable(false);
        btnLogout.setRequestFocusEnabled(false);
        btnLogout.setRolloverEnabled(false);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 160, 40));

        HIA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        HIA.setForeground(new java.awt.Color(255, 255, 255));
        HIA.setText("Add HIA Artist");
        HIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HIAMouseClicked(evt);
            }
        });
        getContentPane().add(HIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        iRecord.log("Logging out..");
        iRecord.setLoggedUser(null);
        setVisible(false);
        dispose();
        iRecord.log("Successfully logged out");
        
        LoginGui tmp = new LoginGui();
        iRecord.log("Activating login screen");
        tmp.setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked
    
    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        iRecord.log("Quitting MuzaMusic");
        XMLManager.ExportXML();
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked
    
    private void btnViewReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewReportMouseClicked
        // frmViewReport add = new frmViewReport();
        // iWindow.openWin(add);
    }//GEN-LAST:event_btnViewReportMouseClicked
    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed
    
    private void ArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArtistMouseClicked
        closeAllPanels();
        AR.setVisible(true);
        updateWin();
    }//GEN-LAST:event_ArtistMouseClicked
    
    private void FreelancerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FreelancerMouseClicked
        closeAllPanels();
        FL.setVisible(true);
        updateWin();
    }//GEN-LAST:event_FreelancerMouseClicked
    
    private void WatchRegisteredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WatchRegisteredMouseClicked
        closeAllPanels();
        frmRegReport add = new frmRegReport();
        iWindow.openWin(add);
    }//GEN-LAST:event_WatchRegisteredMouseClicked
    
    private void AddStudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStudioMouseClicked
        closeAllPanels();
        frmAddStudio add = new frmAddStudio();
        iWindow.openWin(add);
    }//GEN-LAST:event_AddStudioMouseClicked
    
    private void AddRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddRoomMouseClicked
        closeAllPanels();
        frmAddRoom add = new frmAddRoom();
        iWindow.openWin(add);
    }//GEN-LAST:event_AddRoomMouseClicked
    
    private void SuspendArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuspendArtistMouseClicked
        closeAllPanels();
        frmArtistSuspension add = new frmArtistSuspension();
        iWindow.openWin(add);
    }//GEN-LAST:event_SuspendArtistMouseClicked
    
    private void AddArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddArtistMouseClicked
        closeAllPanels();
        frmAddArtist add = new frmAddArtist();
        iWindow.openWin(add);
    }//GEN-LAST:event_AddArtistMouseClicked
    
    private void StudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudioMouseClicked
        closeAllPanels();
        STD.setVisible(true);
        updateWin();
    }//GEN-LAST:event_StudioMouseClicked
    
    private void ExpertiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpertiseMouseClicked
        closeAllPanels();
        frmAddExpertise add = new frmAddExpertise();
        iWindow.openWin(add);
    }//GEN-LAST:event_ExpertiseMouseClicked
    
    private void SessionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SessionsMouseClicked
        closeAllPanels();
        String id = JOptionPane.showInputDialog("Please insert artist ID");
        if (!ArtistManager.isExists(id)){
            JOptionPane.showMessageDialog(null, "Artist was not found");
            updateWin();
            return;
        }
        
        frmSessionsReport add = new frmSessionsReport(id);
        iWindow.openWin(add);
    }//GEN-LAST:event_SessionsMouseClicked
    
    private void ARFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ARFocusLost
        closeAllPanels();
        updateWin();
    }//GEN-LAST:event_ARFocusLost
    
    private void STDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_STDFocusLost
        closeAllPanels();
        updateWin();
    }//GEN-LAST:event_STDFocusLost
    
    private void ContentFrameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContentFrameMouseEntered
        closeAllPanels();
        updateWin();
    }//GEN-LAST:event_ContentFrameMouseEntered
    
    private void CreateSession1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateSession1MouseClicked
        frmCreateSession add = new frmCreateSession();
        iWindow.openWin(add);
    }//GEN-LAST:event_CreateSession1MouseClicked
    
    private void WatchRegistered1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WatchRegistered1MouseClicked
        frmRegReport add = new frmRegReport();
        iWindow.openWin(add);
    }//GEN-LAST:event_WatchRegistered1MouseClicked
    
    private void Sessions1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sessions1MouseClicked
        frmSessions add = new frmSessions();
        iWindow.openWin(add);
    }//GEN-LAST:event_Sessions1MouseClicked
    
    private void FLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FLFocusLost
        closeAllPanels();
        updateWin();
    }//GEN-LAST:event_FLFocusLost
    
    private void SuspendFreelancer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuspendFreelancer1MouseClicked
        closeAllPanels();
        frmFreelancerToStudio add = new frmFreelancerToStudio();
        iWindow.openWin(add);
    }//GEN-LAST:event_SuspendFreelancer1MouseClicked
    
    private void SuspendFreelancerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuspendFreelancerMouseClicked
        closeAllPanels();
        frmFreelancerSuspension add = new frmFreelancerSuspension();
        iWindow.openWin(add);
    }//GEN-LAST:event_SuspendFreelancerMouseClicked
    
    private void AddMusicianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMusicianMouseClicked
        closeAllPanels();
        frmAddMusician add = new frmAddMusician();
        iWindow.openWin(add);
    }//GEN-LAST:event_AddMusicianMouseClicked
    
    private void AddSoundmanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSoundmanMouseClicked
        closeAllPanels();
        frmAddSoundman add = new frmAddSoundman();
        iWindow.openWin(add);
    }//GEN-LAST:event_AddSoundmanMouseClicked
    
    private void joinStudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinStudioMouseClicked
        frmFreelancerJoinStudio add = new frmFreelancerJoinStudio();
        iWindow.openWin(add);
    }//GEN-LAST:event_joinStudioMouseClicked
    
    private void WatchRegistered2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WatchRegistered2MouseClicked
        frmRegReport add = new  frmRegReport();
        iWindow.openWin(add);
    }//GEN-LAST:event_WatchRegistered2MouseClicked
    
    private void Sessions2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sessions2MouseClicked
        frmFreelancerSessions add = new frmFreelancerSessions();
        iWindow.openWin(add);
    }//GEN-LAST:event_Sessions2MouseClicked
    
    private void musicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicMouseClicked
        Musician m = FreelancerManager.getMuicianDetails(iRecord.getLoggedUser().getID());
        if (m != null){
            frmAddMusician add = new frmAddMusician(m);
            iWindow.openWin(add);
        }
        return;
        
    }//GEN-LAST:event_musicMouseClicked
    
    private void soundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soundMouseClicked
        Soundman s = FreelancerManager.getSoundmanDetails(iRecord.getLoggedUser().getID());
        if (s != null){
            frmAddSoundman add = new frmAddSoundman(s);
            iWindow.openWin(add);
        }
        return;
    }//GEN-LAST:event_soundMouseClicked

    private void HIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HIAMouseClicked
        
    }//GEN-LAST:event_HIAMouseClicked
    
    private void closeAllPanels(){
        AR.setVisible(false);
        updateWin();
        FL.setVisible(false);
        updateWin();
        STD.setVisible(false);
        updateWin();
    }
    
    public void refreshVars() {
        lblTitle.setText("Homepage");
        lblUserType.setText("" + iRecord.getLoggedUser().getUserAuth());
        //System.out.println(iRecord.getLoggedUser().getUserAuth());
        lblUsernames.setText(iRecord.getLoggedUser().getID()+ " " + iRecord.getLoggedUser().getStageName());
        pnlAdmin.setVisible(false);
        AR.setVisible(false);
        FL.setVisible(false);
        STD.setVisible(false);
        HIA.setVisible(false);
        pnlFreelancer.setVisible(false);
        pnlArtist.setVisible(false);
        switch (iRecord.getLoggedUser().getUserAuth()) {
            case Artist:
                pnlArtist.setVisible(true);
                break;
                
            case Freelancer:
                pnlFreelancer.setVisible(true);
                break;
                
            case Administrator:
                pnlAdmin.setVisible(true);
                break;
                
            case HIA_Artist:
                HIA.setVisible(true);
                Artist a = (Artist)iRecord.getLoggedUser();
                a.setUserAuth(EAuth.HIA_Artist);
                frmAddArtist add = new frmAddArtist(a.getID(), a.getStageName(), a.getEmail());
                iWindow.openWin(add);
                break;
        }
        
    }
    
    
    public void updateWin(){
        
        iWindow.update();
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AR;
    private javax.swing.JLabel AddArtist;
    private javax.swing.JLabel AddMusician;
    private javax.swing.JLabel AddRoom;
    private javax.swing.JLabel AddSoundman;
    private javax.swing.JLabel AddStudio;
    private javax.swing.JLabel Artist;
    private javax.swing.JPanel ContentFrame;
    private javax.swing.JLabel CreateSession1;
    private javax.swing.JLabel Expertise;
    private javax.swing.JPanel FL;
    private javax.swing.JLabel Freelancer;
    private javax.swing.JLabel HIA;
    private javax.swing.JPanel STD;
    private javax.swing.JLabel Sessions;
    private javax.swing.JLabel Sessions1;
    private javax.swing.JLabel Sessions2;
    private javax.swing.JLabel Studio;
    private javax.swing.JLabel SuspendArtist;
    private javax.swing.JLabel SuspendFreelancer;
    private javax.swing.JLabel SuspendFreelancer1;
    private javax.swing.JLabel WatchRegistered;
    private javax.swing.JLabel WatchRegistered1;
    private javax.swing.JLabel WatchRegistered2;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel joinStudio;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblUsernames;
    private javax.swing.JLabel music;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlArtist;
    private javax.swing.JPanel pnlFreelancer;
    private javax.swing.JLabel sound;
    // End of variables declaration//GEN-END:variables
    
}
